### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by BigAlzBub** [DevDyna/IronBerry#12]
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

Ironberry Expert 0.8b

### Description

When I open the Journal of Alchemy it doesn't provide any information, instead there is the red Text "Loading Error!"
Additionally, when I try to use the Roots Classic Fruits (such as Black current or White Current) in the mechanical squeezer, it doesn't do anything, the fruit just sits in the input slot and doesn't process.

### Procedure

For the journal, you just place it in the hot bar and then activate the slot.
For the Squeezer, nothing special is required.

### Additional things

![Alchemy](https://github.com/DevDyna/IronBerry/assets/162751210/af4fd233-8276-47d4-afb0-ca15ebac9398)

**Comment by DevDyna** [comment]
yeah it was a _known issue_ that it dont have long life!
it was caused by `reactive` mod and he fixed it but i didn't updated due priority issues [it was on this [commit](https://github.com/DevDyna/IronBerry/compare/c0f09cd8ba7c...3a178c06942f)]
you can do two options:
- if you want "a easy/temp fix" without wait you can update `reactive`
-  wait until the new upload that include full chapter 5 playable (a few of days or weeks)

**Comment by DevDyna** [comment]
[0.8d release]
